export interface Venda {
  id: string;
  clienteId: string;
  empreendimentoId: string;
  numeroLote: string;
  quadra: string;
  rua?: string;
  valorLote: number;
  valorEntrada: number;
  quantidadeParcelas: number;
  valorParcela: number;
  dataVencimento: string;
  dataVenda: string;
  vendedor: string;
  vendedorId?: string;
  status: "ativo" | "pago" | "atrasado" | "cancelado" | "pendente" | "rascunho";
  formaPagamento?: string;
  custo?: number;
  comissao?: number;
  user_id?: string;
  modoAvista?: "dinheiro" | "pix" | "cheque" | "permuta" | "outro";
  descricaoAvista?: string;
  numeroContrato?: string;
  clienteNome?: string;
  empreendimentoNome?: string;
  contratoGerado?: boolean;
  rascunho?: boolean;
  medidaFrente?: string;
  medidaLateralDir?: string;
  medidaLateralEsq?: string;
  medidaFundos?: string;
  areaTotal?: string;
  comprador2?: any;
}
